(rule
 (target vm)
 (mode
  (promote (until-clean)))
 (deps Makefile main.c vm.c vm.h bytecode.c bytecode.h state.c state.h callstack.c callstack.h error.h ../runtime/runtime.a)
 (action
  (run make)))

(rule
 (target vm-allsan)
 (mode
  (promote (until-clean)))
 (deps Makefile main.c vm.c vm.h bytecode.c bytecode.h state.c state.h callstack.c callstack.h error.h ../runtime/runtime.a)
 (action
  (run make vm-allsan)))