(rule
 (target vmver)
 (mode
  (promote (until-clean)))
 (deps Makefile vmver.c verify.cc verify_run.h state.h callstack.h csval.h error.h verify.hh ../byterun/bytefile.h ../byterun/bytefile.c ../byterun/disasm.h ../runtime/runtime.a)
 (action
  (run make)))

(rule
 (target vmver-allsan)
 (mode
  (promote (until-clean)))
 (deps Makefile vmver.c verify.cc verify_run.h state.h callstack.h csval.h error.h verify.hh ../byterun/bytefile.h ../byterun/bytefile.c ../byterun/disasm.h ../runtime/runtime.a)
 (action
  (run make vmver-allsan)))

(cram (deps ../src/Driver.exe ../runtime/Std.i))

(cram (applies_to Sort)
  (deps performance/Sort.lama vmver-allsan ../src/Driver.exe ../runtime/Std.i))